language: perl
perl:
  - "5.21"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
install:
  - cpanm --quiet --notest Module::Install Module::Install::ReadmeFromPod Module::Install::AuthorTests Package::Variant DBI XML::LibXML
  - cpanm --notest git://github.com/SysPete/sql-translator.git@topic/producer_postgresql_batch_alter_table || cat /home/travis/.cpanm/work/*/build.log
  - cpanm --quiet --notest DBD::Pg http://cpan.metacpan.org/authors/id/T/TJ/TJC/Test-PostgreSQL-1.02.tar.gz DBD::mysql Test::mysqld
  - cpanm --quiet --installdeps --notest .
