language: perl
perl:
  - "5.19"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
env:
  - TEST_DBIC=1
install:
  - cpanm --quiet --notest DBD::Pg Test::PostgreSQL DBD::mysql Test::mysqld
  - cpanm --quiet --installdeps --notest .
